# Generated by Django 5.1.7 on 2025-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('brand', models.IntegerField()),
                ('range', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
